#server:
#  port: 8080
#spring:
#    jpa:
#        database: MYSQL
#        hibernate:
#            ddl-auto: update
#
#    datasource:
#        url: jdbc:mysql://eu-cdbr-west-01.cleardb.com:3306/heroku_8249edd78006894??sslmode=require
#        username: b5de5fedfca664
#        password: 1eb89a02
#        name: heroku_8249edd78006894
#        driver-class-name: com.mysql.jdbc.Driver